version: "3.8"

services:
    web:
        build:
            context: ./docker/bin/${DOCKER_PHP}
        container_name: "${DOCKER}-${DOCKER_PHP}"
        restart: "always"
        ports:
            - "81:80"
            - "443:443"
        links:
            - mysql
        volumes:
            - .:/var/www/html
            - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/config/sites:/etc/apache2/sites-enabled
            - ./docker/logs/httpd:/var/log/apache2
        environment:
            PMA_PORT: ${PMA_PORT}
    mysql:
        build:
            context: "./docker/bin/${DOCKER_DB}"
        container_name: "${DOCKER}-mysql"
        restart: "always"
        ports:
            - "127.0.0.1:${DB_PORT}:3306"
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
            - ./docker/logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "${DOCKER}-phpmyadmin"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${PMA_PORT}:80"
        volumes:
            - /sessions
            - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    redis:
        container_name: "${DOCKER}-redis"
        image: redis:latest
        ports:
            - "127.0.0.1:${REDIS_PORT}:6379"
