version: "3.8"

services:
    mysql:
        build:
            context: "./docker/bin/mysql"
        container_name: "${DOCKER}-mysql"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
            timeout: 10s
            retries: 30
        ports:
            - "3306:3306"
        restart: "always"
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
            - ./docker/logs/mysql:/var/log/mysql
    redis:
        container_name: "${DOCKER}-redis"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 3s
            retries: 30
        image: redis:latest
        ports:
            - "6379:6379"
    web:
        build:
            context: ./docker/bin/php
        container_name: "${DOCKER}-php"
        depends_on:
            - mysql
            - redis
        healthcheck:
            test: ["CMD", "/usr/local/bin/healthcheck", "localhost"]
            timeout: 10s
            retries: 30
        ports:
            - "80:80"
        restart: "always"
        volumes:
            - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/config/sites:/etc/apache2/sites-enabled
            - ./docker/logs/httpd:/var/log/apache2
            - .:/var/www/html
